spring.application.name=ProyectoSGOVI

# La URL correcta apuntando al servidor de la universidad
spring.datasource.url=jdbc:postgresql://db-aules.uji.es:5432/ei102725sps?ssl=true&sslmode=require
spring.datasource.username=ei102725sps
spring.datasource.password=ei102725sps

# Opcional: Esto ayuda a ver los errores de SQL mas claros en la consola
spring.jpa.show-sql=true
